name: Release

on:
  push:
    branches:
      - master
      - main

jobs:
  release:
    uses: cy-cypn/release-actions/.github/workflows/release.yml@main
    secrets:
      app-id: ${{ secrets.RELEASE_ACTION_APP_ID }}
      private-key: ${{ secrets.RELEASE_ACTION_PRIVATE_KEY }}
      dotenv-prod: ${{ secrets.DOTENV_PROD }} #認証情報が必要ないなら設定しなくてもOK
